#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-6-sol"
model_reasoning_effort = "high"
service_tier = "fast"
notify = ["/Users/sherwin/cfg/Codex/notify.sh"]

[marketplaces.claude-plugins-official]
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."vercel@claude-plugins-official"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"
